version: '3.8'

services:
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dashboard
    restart: always
    ports:
      - "8083:80"
    volumes:
      - ./html:/var/www/html
    networks:
      - nosferatus

networks:
  nosferatus:
    external: true

